### ISSUE TITLE
Ze Zendesku: blbej čas u autorizace

### ISSUE THREAD

**Issue by padak** [keboola/kbc-ui-ex-twitter#1]
Ahoj,

Twitter ex ma nejakej problem s casovejma zonama. Kdyz jsem zridil novou konfiguraci, tak tvrdi ze prej ji udelam az za devet hodin (rozdil mezi CET a PST): https://www.evernote.com/l/ACDZJbeDbtVCe57E8ttHFlKkCVuyA70SqGA

**Comment by padak** [comment]
(snad to patří sem - nevím moc kam tohle směrovat)

**Comment by Halama** [comment]
všechno co se týče ui sem https://github.com/keboola/kbc-ui/issues
Tohle je něco starýho, ui máme ted celé jako jeden projekt.

**Comment by padak** [comment]
díky! Je to tady: https://github.com/keboola/kbc-ui/issues/677
